//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.10.27 at 04:49:23 PM MSD
//


package ru.crystals.pos.customerdisplay.ksdp01.templates.parser;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fontSize.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="fontSize">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FS10x16"/>
 *     &lt;enumeration value="FS12x24"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "fontSize")
@XmlEnum
public enum FontSize {

    @XmlEnumValue("FS10x16")
    FS_10_X_16("FS10x16"),
    @XmlEnumValue("FS12x24")
    FS_12_X_24("FS12x24");
    private final String value;

    FontSize(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FontSize fromValue(String v) {
        for (FontSize c : FontSize.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
