//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2011.10.27 at 04:49:23 PM MSD
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://crystals.ru/pos/customerdisplay/ksdp01/templates/parser", elementFormDefault =
        javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.crystals.pos.customerdisplay.ksdp01.templates.parser;
