//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.09.23 at 06:45:21 PM MSK
//
package ru.crystals.pos.bank.softcase.utils;

import org.apache.commons.lang.StringUtils;
import ru.crystals.pos.bank.datastruct.RefundData;
import ru.crystals.pos.bank.datastruct.ReversalData;
import ru.crystals.pos.bank.datastruct.SaleData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import java.nio.charset.Charset;
import java.util.Date;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p/>
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * <p/>
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="kkm" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="code" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="type" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="card" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="track3" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="trace" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="tdt" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="expdt" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="rrn" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="auth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="termid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="resp" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="cardholder" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="applabel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="aid" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="trancert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="pem" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="cardid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="crc" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "mess",
        propOrder = {"kkm", "code", "type", "card", "track3", "amount", "trace", "tdt", "expdt", "rrn", "auth", "termid", "resp", "cardholder",
                "applabel", "aid", "trancert", "pem", "cardid", "crc"})
@XmlRootElement(name = "mess")
public class SoftCaseMessage {

    public static final String PAY_TYPE = "0200000000";
    public static final String PAY_ANSWER_TYPE = "0210000000";
    public static final String REVERSAL_TYPE = "0400000000";
    public static final String REVERSAL_ANSWER_TYPE = "0410000000";
    public static final String REFUND_TYPE = "0200200000";
    public static final String REFUND_ANSWER_TYPE = "0210200000";
    public static final String DAILY_LOG_TYPE = "0520000000";
    public static final String DAILY_LOG_ANSWER_TYPE = "0530000000";

    protected Long kkm;
    protected String code;
    protected String type;
    protected String card;
    protected String track3;
    protected Long amount;
    protected Long trace;
    protected Long tdt;
    protected Integer expdt;
    protected Long rrn;
    protected String auth;
    protected Integer termid;
    protected String resp;
    protected String cardholder;
    protected String applabel;
    protected String aid;
    protected String trancert;
    protected String pem;
    protected Integer cardid;
    protected String crc;

    public SoftCaseMessage() {
    }

    public SoftCaseMessage(SaleData saleData) {
        this.amount = saleData.getAmount();
        this.type = PAY_TYPE;
        this.crc = MD5(getStringForHash());
    }

    public SoftCaseMessage(RefundData saleData) {
        this.amount = saleData.getAmount();
        this.type = REFUND_TYPE;
        this.trace = saleData.getRefNumber() != null ? Long.parseLong(saleData.getRefNumber()) : null;
        this.crc = MD5(getStringForHash());
    }

    public SoftCaseMessage(ReversalData saleData) {
        this.amount = saleData.getAmount();
        this.type = REVERSAL_TYPE;
        this.trace = Long.parseLong(saleData.getRefNumber());
        this.crc = MD5(getStringForHash());
    }

    public SoftCaseMessage(Long kkm) {
        this.kkm = kkm;
        this.type = DAILY_LOG_TYPE;
        this.crc = MD5(getStringForHash());
    }

    /**
     * Gets the value of the kkm property.
     */
    public Long getKkm() {
        return kkm;
    }

    /**
     * Sets the value of the kkm property.
     */
    public void setKkm(Long value) {
        this.kkm = value;
    }

    /**
     * Gets the value of the code property.
     */
    public String getCode() {
        return StringUtils.isNotEmpty(code) && code.length() < 2 ? "0" + code : code;
    }

    /**
     * Sets the value of the code property.
     */
    public void setCode(String value) {
        this.code = value;
    }

    /**
     * Gets the value of the type property.
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the card property.
     *
     * @return possible object is {@link String }
     */
    public String getCard() {
        return card;
    }

    /**
     * Sets the value of the card property.
     *
     * @param value allowed object is {@link String }
     */
    public void setCard(String value) {
        this.card = value;
    }

    /**
     * Gets the value of the track3 property.
     *
     * @return possible object is {@link String }
     */
    public String getTrack3() {
        return track3;
    }

    /**
     * Sets the value of the track3 property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTrack3(String value) {
        this.track3 = value;
    }

    /**
     * Gets the value of the amount property.
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     */
    public void setAmount(long value) {
        this.amount = value;
    }

    /**
     * Gets the value of the trace property.
     */
    public Long getTrace() {
        return trace;
    }

    /**
     * Sets the value of the trace property.
     */
    public void setTrace(Long value) {
        this.trace = value;
    }

    /**
     * Gets the value of the tdt property.
     */
    public Date getTdt() {
        return new Date(tdt);
    }

    /**
     * Sets the value of the tdt property.
     */
    public void setTdt(Long value) {
        this.tdt = value;
    }

    /**
     * Gets the value of the expdt property.
     *
     * @return possible object is {@link javax.xml.datatype.XMLGregorianCalendar }
     */
    public Integer getExpdt() {
        return expdt;
    }

    /**
     * Sets the value of the expdt property.
     *
     * @param value allowed object is {@link javax.xml.datatype.XMLGregorianCalendar }
     */
    public void setExpdt(Integer value) {
        this.expdt = value;
    }

    /**
     * Gets the value of the rrn property.
     */
    public Long getRrn() {
        return rrn;
    }

    /**
     * Sets the value of the rrn property.
     */
    public void setRrn(Long value) {
        this.rrn = value;
    }

    /**
     * Gets the value of the auth property.
     */
    public String getAuth() {
        return auth;
    }

    /**
     * Sets the value of the auth property.
     */
    public void setAuth(String value) {
        this.auth = value;
    }

    /**
     * Gets the value of the termid property.
     */
    public int getTermid() {
        return termid;
    }

    /**
     * Sets the value of the termid property.
     */
    public void setTermid(int value) {
        this.termid = value;
    }

    /**
     * Gets the value of the resp property.
     *
     * @return possible object is {@link String }
     */
    public String getResp() {
        return resp;
    }

    /**
     * Sets the value of the resp property.
     *
     * @param value allowed object is {@link String }
     */
    public void setResp(String value) {
        this.resp = value;
    }

    /**
     * Gets the value of the cardholder property.
     *
     * @return possible object is {@link String }
     */
    public String getCardholder() {
        return cardholder;
    }

    /**
     * Sets the value of the cardholder property.
     *
     * @param value allowed object is {@link String }
     */
    public void setCardholder(String value) {
        this.cardholder = value;
    }

    /**
     * Gets the value of the applabel property.
     *
     * @return possible object is {@link String }
     */
    public String getApplabel() {
        return applabel;
    }

    /**
     * Sets the value of the applabel property.
     *
     * @param value allowed object is {@link String }
     */
    public void setApplabel(String value) {
        this.applabel = value;
    }

    /**
     * Gets the value of the aid property.
     *
     * @return possible object is {@link String }
     */
    public String getAid() {
        return aid;
    }

    /**
     * Sets the value of the aid property.
     *
     * @param value allowed object is {@link String }
     */
    public void setAid(String value) {
        this.aid = value;
    }

    /**
     * Gets the value of the trancert property.
     *
     * @return possible object is {@link String }
     */
    public String getTrancert() {
        return trancert;
    }

    /**
     * Sets the value of the trancert property.
     *
     * @param value allowed object is {@link String }
     */
    public void setTrancert(String value) {
        this.trancert = value;
    }

    /**
     * Gets the value of the pem property.
     */
    public String getPem() {
        return pem;
    }

    /**
     * Sets the value of the pem property.
     */
    public void setPem(String value) {
        this.pem = value;
    }

    /**
     * Gets the value of the cardid property.
     */
    public int getCardid() {
        return cardid;
    }

    /**
     * Sets the value of the cardid property.
     */
    public void setCardid(int value) {
        this.cardid = value;
    }

    /**
     * Gets the value of the crc property.
     *
     * @return possible object is {@link String }
     */
    public String getCrc() {
        return crc;
    }

    /**
     * Sets the value of the crc property.
     *
     * @param value allowed object is {@link String }
     */
    public void setCrc(String value) {
        this.crc = value;
    }

    public static String MD5(String md5) {
        try {
            java.security.MessageDigest md = java.security.MessageDigest.getInstance("MD5");
            byte[] array = md.digest(md5.getBytes(Charset.forName("UTF-8")));
            StringBuffer sb = new StringBuffer();
            for (int i = 0; i < array.length; ++i) {
                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1, 3));
            }
            return sb.toString();
        } catch (java.security.NoSuchAlgorithmException e) {
            //
        }
        return null;
    }

    private String getStringForHash() {
        StringBuilder result = new StringBuilder();
        if (code != null) {
            result.append(code);
        }
        if (StringUtils.isNotBlank(type)) {
            result.append(type);
        }
        if (StringUtils.isNotBlank(card)) {
            result.append(card);
        }
        if (amount != null) {
            result.append(amount);
        }
        if (kkm != null) {
            result.append(kkm);
        }
        if (tdt != null) {
            result.append(tdt);
        }
        if (expdt != null) {
            result.append(expdt);
        }
        if (rrn != null) {
            result.append(rrn);
        }
        if (StringUtils.isNotBlank(auth)) {
            result.append(auth);
        }
        if (StringUtils.isNotBlank(resp)) {
            result.append(resp);
        }
        return result.toString();
    }

    @Override
    public String toString() {
        return "SoftCaseMessage{" +
                "kkm=" + kkm +
                ", code=" + code +
                ", type='" + type + '\'' +
                ", card='" + card + '\'' +
                ", track3='" + track3 + '\'' +
                ", amount=" + amount +
                ", trace=" + trace +
                ", tdt=" + tdt +
                ", expdt=" + expdt +
                ", rrn=" + rrn +
                ", auth='" + auth + '\'' +
                ", termid=" + termid +
                ", resp='" + resp + '\'' +
                ", cardholder='" + cardholder + '\'' +
                ", applabel='" + applabel + '\'' +
                ", aid='" + aid + '\'' +
                ", trancert='" + trancert + '\'' +
                ", pem=" + pem +
                ", cardid=" + cardid +
                ", crc='" + crc + '\'' +
                '}';
    }
}
