
package jp.co.glory.bruebox;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "BrueBoxPortType", targetNamespace = "http://www.glory.co.jp/bruebox.wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BrueBoxPortType {


    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.OccupyResponseType
     */
    @WebMethod(operationName = "OccupyOperation", action = "OccupyOperation")
    @WebResult(name = "OccupyResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public OccupyResponseType occupyOperation(
        @WebParam(name = "OccupyRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        OccupyRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.ReleaseResponseType
     */
    @WebMethod(operationName = "ReleaseOperation", action = "ReleaseOperation")
    @WebResult(name = "ReleaseResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public ReleaseResponseType releaseOperation(
        @WebParam(name = "ReleaseRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        ReleaseRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.StatusResponseType
     */
    @WebMethod(operationName = "GetStatus", action = "GetStatus")
    @WebResult(name = "StatusResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public StatusResponseType getStatus(
        @WebParam(name = "StatusRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        StatusRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.OpenResponseType
     */
    @WebMethod(operationName = "OpenOperation", action = "OpenOperation")
    @WebResult(name = "OpenResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public OpenResponseType openOperation(
        @WebParam(name = "OpenRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        OpenRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.CloseResponseType
     */
    @WebMethod(operationName = "CloseOperation", action = "CloseOperation")
    @WebResult(name = "CloseResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public CloseResponseType closeOperation(
        @WebParam(name = "CloseRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        CloseRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.ChangeResponseType
     */
    @WebMethod(operationName = "ChangeOperation", action = "ChangeOperation")
    @WebResult(name = "ChangeResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public ChangeResponseType changeOperation(
        @WebParam(name = "ChangeRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        ChangeRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.ChangeCancelResponseType
     */
    @WebMethod(operationName = "ChangeCancelOperation", action = "ChangeCancelOperation")
    @WebResult(name = "ChangeCancelResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public ChangeCancelResponseType changeCancelOperation(
        @WebParam(name = "ChangeCancelRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        ChangeCancelRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.StartCashinResponseType
     */
    @WebMethod(operationName = "StartCashinOperation", action = "StartCashinOperation")
    @WebResult(name = "StartCashinResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public StartCashinResponseType startCashinOperation(
        @WebParam(name = "StartCashinRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        StartCashinRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.EndCashinResponseType
     */
    @WebMethod(operationName = "EndCashinOperation", action = "EndCashinOperation")
    @WebResult(name = "EndCashinResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public EndCashinResponseType endCashinOperation(
        @WebParam(name = "EndCashinRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        EndCashinRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.CashinCancelResponseType
     */
    @WebMethod(operationName = "CashinCancelOperation", action = "CashinCancelOperation")
    @WebResult(name = "CashinCancelResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public CashinCancelResponseType cashinCancelOperation(
        @WebParam(name = "CashinCancelRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        CashinCancelRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.CashoutResponseType
     */
    @WebMethod(operationName = "CashoutOperation", action = "CashoutOperation")
    @WebResult(name = "CashoutResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public CashoutResponseType cashoutOperation(
        @WebParam(name = "CashoutRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        CashoutRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.InventoryResponseType
     */
    @WebMethod(operationName = "InventoryOperation", action = "InventoryOperation")
    @WebResult(name = "InventoryResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public InventoryResponseType inventoryOperation(
        @WebParam(name = "InventoryRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        InventoryRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.ResetResponseType
     */
    @WebMethod(operationName = "ResetOperation", action = "ResetOperation")
    @WebResult(name = "ResetResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public ResetResponseType resetOperation(
        @WebParam(name = "ResetRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        ResetRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.CollectResponseType
     */
    @WebMethod(operationName = "CollectOperation", action = "CollectOperation")
    @WebResult(name = "CollectResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public CollectResponseType collectOperation(
        @WebParam(name = "CollectRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        CollectRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.CounterClearResponseType
     */
    @WebMethod(operationName = "CounterClearOperation", action = "CounterClearOperation")
    @WebResult(name = "CounterClearResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public CounterClearResponseType counterClearOperation(
        @WebParam(name = "CounterClearRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        CounterClearRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.RegisterEventResponseType
     */
    @WebMethod(operationName = "RegisterEventOperation", action = "RegisterEventOperation")
    @WebResult(name = "RegisterEventResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public RegisterEventResponseType registerEventOperation(
        @WebParam(name = "RegisterEventRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        RegisterEventRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.UnRegisterEventResponseType
     */
    @WebMethod(operationName = "UnRegisterEventOperation", action = "UnRegisterEventOperation")
    @WebResult(name = "UnRegisterEventResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public UnRegisterEventResponseType unRegisterEventOperation(
        @WebParam(name = "UnRegisterEventRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        UnRegisterEventRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.EventNotificationStatusResponseType
     */
    @WebMethod(operationName = "EventNotificationStatusOperation", action = "EventNotificationStatusOperation")
    @WebResult(name = "EventNotificationStatusResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public EventNotificationStatusResponseType eventNotificationStatusOperation(
        @WebParam(name = "EventNotificationStatusRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        EventNotificationStatusRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.LoginUserResponseType
     */
    @WebMethod(operationName = "LoginUserOperation", action = "LoginUserOperation")
    @WebResult(name = "LoginUserResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public LoginUserResponseType loginUserOperation(
        @WebParam(name = "LoginUserRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        LoginUserRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.LogoutUserResponseType
     */
    @WebMethod(operationName = "LogoutUserOperation", action = "LogoutUserOperation")
    @WebResult(name = "LogoutUserResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public LogoutUserResponseType logoutUserOperation(
        @WebParam(name = "LogoutUserRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        LogoutUserRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.RomVersionResponseType
     */
    @WebMethod(operationName = "RomVersionOperation", action = "RomVersionOperation")
    @WebResult(name = "RomVersionResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public RomVersionResponseType romVersionOperation(
        @WebParam(name = "RomVersionRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        RomVersionRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.StartDownloadResponseType
     */
    @WebMethod(operationName = "StartDownloadOperation", action = "StartDownloadOperation")
    @WebResult(name = "StartDownloadResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public StartDownloadResponseType startDownloadOperation(
        @WebParam(name = "StartDownload", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        StartDownloadRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.StartLogreadResponseType
     */
    @WebMethod(operationName = "StartLogreadOperation", action = "StartLogreadOperation")
    @WebResult(name = "StartLogreadResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public StartLogreadResponseType startLogreadOperation(
        @WebParam(name = "StartLogread", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        StartLogreadRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.UpdateManualDepositTotalResponseType
     */
    @WebMethod(operationName = "UpdateManualDepositTotalOperation", action = "UpdateManualDepositTotalOperation")
    @WebResult(name = "UpdateManualDepositTotalResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public UpdateManualDepositTotalResponseType updateManualDepositTotalOperation(
        @WebParam(name = "UpdateManualDepositTotalRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        UpdateManualDepositTotalRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.RefreshSalesTotalResponseType
     */
    @WebMethod(operationName = "RefreshSalesTotalOperation", action = "RefreshSalesTotalOperation")
    @WebResult(name = "RefreshSalesTotalResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public RefreshSalesTotalResponseType refreshSalesTotalOperation(
        @WebParam(name = "RefreshSalesTotalRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        RefreshSalesTotalRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.ReturnCashResponseType
     */
    @WebMethod(operationName = "ReturnCashOperation", action = "ReturnCashOperation")
    @WebResult(name = "ReturnCashResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public ReturnCashResponseType returnCashOperation(
        @WebParam(name = "ReturnCashRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        ReturnCashRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.EnableDenomResponseType
     */
    @WebMethod(operationName = "EnableDenomOperation", action = "EnableDenomOperation")
    @WebResult(name = "EnableDenomResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public EnableDenomResponseType enableDenomOperation(
        @WebParam(name = "EnableDenomRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        EnableDenomRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.DisableDenomResponseType
     */
    @WebMethod(operationName = "DisableDenomOperation", action = "DisableDenomOperation")
    @WebResult(name = "DisableDenomResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public DisableDenomResponseType disableDenomOperation(
        @WebParam(name = "DisableDenomRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        DisableDenomRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.PowerControlResponseType
     */
    @WebMethod(operationName = "PowerControlOperation", action = "PowerControlOperation")
    @WebResult(name = "PowerControlResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public PowerControlResponseType powerControlOperation(
        @WebParam(name = "PowerControlRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        PowerControlRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.AdjustTimeResponseType
     */
    @WebMethod(operationName = "AdjustTimeOperation", action = "AdjustTimeOperation")
    @WebResult(name = "AdjustTimeResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public AdjustTimeResponseType adjustTimeOperation(
        @WebParam(name = "AdjustTimeRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        AdjustTimeRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.StartReplenishmentFromEntranceResponseType
     */
    @WebMethod(operationName = "StartReplenishmentFromEntranceOperation", action = "StartReplenishmentFromEntranceOperation")
    @WebResult(name = "StartReplenishmentFromEntranceResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public StartReplenishmentFromEntranceResponseType startReplenishmentFromEntranceOperation(
        @WebParam(name = "StartReplenishmentFromEntranceRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        StartReplenishmentFromEntranceRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.EndReplenishmentFromEntranceResponseType
     */
    @WebMethod(operationName = "EndReplenishmentFromEntranceOperation", action = "EndReplenishmentFromEntranceOperation")
    @WebResult(name = "EndReplenishmentFromEntranceResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public EndReplenishmentFromEntranceResponseType endReplenishmentFromEntranceOperation(
        @WebParam(name = "EndReplenishmentFromEntranceRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        EndReplenishmentFromEntranceRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.ReplenishmentFromEntranceCancelResponseType
     */
    @WebMethod(operationName = "ReplenishmentFromEntranceCancelOperation", action = "ReplenishmentFromEntranceCancelOperation")
    @WebResult(name = "ReplenishmentFromEntranceCancelResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public ReplenishmentFromEntranceCancelResponseType replenishmentFromEntranceCancelOperation(
        @WebParam(name = "ReplenishmentFromEntranceCancelRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        ReplenishmentFromEntranceCancelRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.StartReplenishmentFromCassetteResponseType
     */
    @WebMethod(operationName = "StartReplenishmentFromCassetteOperation", action = "StartReplenishmentFromCassetteOperation")
    @WebResult(name = "StartReplenishmentFromCassetteResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public StartReplenishmentFromCassetteResponseType startReplenishmentFromCassetteOperation(
        @WebParam(name = "StartReplenishmentFromCassetteRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        StartReplenishmentFromCassetteRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.EndReplenishmentFromCassetteResponseType
     */
    @WebMethod(operationName = "EndReplenishmentFromCassetteOperation", action = "EndReplenishmentFromCassetteOperation")
    @WebResult(name = "EndReplenishmentFromCassetteResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public EndReplenishmentFromCassetteResponseType endReplenishmentFromCassetteOperation(
        @WebParam(name = "EndReplenishmentFromCassetteRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        EndReplenishmentFromCassetteRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.LockUnitResponseType
     */
    @WebMethod(operationName = "LockUnitOperation", action = "LockUnitOperation")
    @WebResult(name = "LockUnitResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public LockUnitResponseType lockUnitOperation(
        @WebParam(name = "LockUnitRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        LockUnitRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.UnLockUnitResponseType
     */
    @WebMethod(operationName = "UnLockUnitOperation", action = "UnLockUnitOperation")
    @WebResult(name = "UnLockUnitResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public UnLockUnitResponseType unLockUnitOperation(
        @WebParam(name = "UnLockUnitRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        UnLockUnitRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.OpenExitCoverResponseType
     */
    @WebMethod(operationName = "OpenExitCoverOperation", action = "OpenExitCoverOperation")
    @WebResult(name = "OpenExitCoverResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public OpenExitCoverResponseType openExitCoverOperation(
        @WebParam(name = "OpenExitCoverRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        OpenExitCoverRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.CloseExitCoverResponseType
     */
    @WebMethod(operationName = "CloseExitCoverOperation", action = "CloseExitCoverOperation")
    @WebResult(name = "CloseExitCoverResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public CloseExitCoverResponseType closeExitCoverOperation(
        @WebParam(name = "CloseExitCoverRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        CloseExitCoverRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.EventOfflineRecoveryResponseType
     */
    @WebMethod(operationName = "EventOfflineRecoveryOperation", action = "EventOfflineRecoveryOperation")
    @WebResult(name = "EventOfflineRecoveryResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public EventOfflineRecoveryResponseType eventOfflineRecoveryOperation(
        @WebParam(name = "EventOfflineRecoveryRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        EventOfflineRecoveryRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.SetExchangeRateResponseType
     */
    @WebMethod(operationName = "SetExchangeRateOperation", action = "SetExchangeRateOperation")
    @WebResult(name = "SetExchangeRateResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public SetExchangeRateResponseType setExchangeRateOperation(
        @WebParam(name = "SetExchangeRateRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        SetExchangeRateRequestType body);

    /**
     * 
     * @param body
     * @return
     *     returns jp.co.glory.bruebox.UpdateSettingFileResponseType
     */
    @WebMethod(operationName = "UpdateSettingFileOperation", action = "UpdateSettingFileOperation")
    @WebResult(name = "UpdateSettingFileResponse", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
    public UpdateSettingFileResponseType updateSettingFileOperation(
        @WebParam(name = "UpdateSettingFileRequest", targetNamespace = "http://www.glory.co.jp/bruebox.xsd", partName = "body")
        UpdateSettingFileRequestType body);

}
