
package ru.crystals.pos.plugins.purchases;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Set10Purchases", targetNamespace = "http://purchases.erpi.crystals.ru")
public interface Set10Purchases {


    /**
     * 
     * @param purchases
     * @param version
     */
    @WebMethod
    @Oneway
    @RequestWrapper(localName = "processPurchases", targetNamespace = "http://purchases.erpi.crystals.ru", className = "ru.crystals.pos.plugins.purchases.ProcessPurchases")
    @Action(input = "http://purchases.erpi.crystals.ru/inputAction")
    public void processPurchases(
        @WebParam(name = "purchases", targetNamespace = "")
        byte[] purchases,
        @WebParam(name = "version", targetNamespace = "")
        String version);

}
